### ISSUE TITLE
Entering Reading Mode in release build crashes the browser.

### ISSUE THREAD

**Issue by karolba** [anthonycr/Lightning-Browser#186]
This happens at any site:
```
I/ActivityManager(  624): START u0 {cmp=acr.browser.lightning/.ReadingActivity (has extras)} from pid 27973
D/Lightning(27973): onPause
I/ActivityManager(  624): Displayed acr.browser.lightning/.ReadingActivity: +118ms
I/Timeline(27973): Timeline: Activity_idle id: android.os.BinderProxy@651ae0f8 time:111032255
I/Timeline(  624): Timeline: Activity_windows_visible id: ActivityRecord{652cc888 u0 acr.browser.lightning/.ReadingActivity t65} time:111032461
E/Lightning(27973): 200 url:https://news.ycombinator.com/ resolved:null
D/Lightning(27973): no charset found in first stage
D/Lightning(27973): no charset found in second stage
D/Lightning(27973): 24586 FetchAsString:https://news.ycombinator.com/
E/AndroidRuntime(27973): FATAL EXCEPTION: AsyncTask #1
E/AndroidRuntime(27973): Process: acr.browser.lightning, PID: 27973
E/AndroidRuntime(27973): java.lang.RuntimeException: An error occured while executing doInBackground()
E/AndroidRuntime(27973): 	at android.os.AsyncTask$3.done(AsyncTask.java:300)
E/AndroidRuntime(27973): 	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:355)
E/AndroidRuntime(27973): 	at java.util.concurrent.FutureTask.setException(FutureTask.java:222)
E/AndroidRuntime(27973): 	at java.util.concurrent.FutureTask.run(FutureTask.java:242)
E/AndroidRuntime(27973): 	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
E/AndroidRuntime(27973): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
E/AndroidRuntime(27973): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
E/AndroidRuntime(27973): 	at java.lang.Thread.run(Thread.java:811)
E/AndroidRuntime(27973): Caused by: java.lang.ExceptionInInitializerError
E/AndroidRuntime(27973): 	at a.a.b.m.<clinit>(Unknown Source)
E/AndroidRuntime(27973): 	at a.a.b.f.<init>(Unknown Source)
E/AndroidRuntime(27973): 	at a.a.b.e.<init>(Unknown Source)
E/AndroidRuntime(27973): 	at a.a.c.di.b(Unknown Source)
E/AndroidRuntime(27973): 	at a.a.c.di.a(Unknown Source)
E/AndroidRuntime(27973): 	at a.a.c.b.a(Unknown Source)
E/AndroidRuntime(27973): 	at a.a.c.ae.a(Unknown Source)
E/AndroidRuntime(27973): 	at a.a.a.a(Unknown Source)
E/AndroidRuntime(27973): 	at acr.browser.lightning.a.a.a(Unknown Source)
E/AndroidRuntime(27973): 	at acr.browser.lightning.a.a.a(Unknown Source)
E/AndroidRuntime(27973): 	at acr.browser.lightning.a.e.a(Unknown Source)
E/AndroidRuntime(27973): 	at acr.browser.lightning.fe.a(Unknown Source)
E/AndroidRuntime(27973): 	at acr.browser.lightning.fe.doInBackground(Unknown Source)
E/AndroidRuntime(27973): 	at android.os.AsyncTask$2.call(AsyncTask.java:288)
E/AndroidRuntime(27973): 	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
E/AndroidRuntime(27973): 	... 4 more
E/AndroidRuntime(27973): Caused by: java.lang.NullPointerException: in == null
E/AndroidRuntime(27973): 	at java.util.Properties.load(Properties.java:246)
E/AndroidRuntime(27973): 	at a.a.b.l.d(Unknown Source)
E/AndroidRuntime(27973): 	at a.a.b.l.<clinit>(Unknown Source)
E/AndroidRuntime(27973): 	... 19 more
W/ActivityManager(  624):   Force finishing activity acr.browser.lightning/.ReadingActivity
D/Lightning(27973): onResume
I/Timeline(27973): Timeline: Activity_idle id: android.os.BinderProxy@64ce6c88 time:111033712
I/Timeline(  624): Timeline: Activity_windows_visible id: ActivityRecord{65455998 u0 acr.browser.lightning/.MainActivity t65} time:111033943
E/WindowManager(27973):
E/WindowManager(27973): android.view.WindowLeaked: Activity acr.browser.lightning.ReadingActivity has leaked window com.android.internal.policy.impl.PhoneWindow$DecorView{652d8d28 V.E..... R......D 0,0-729,160} that was originally added here
E/WindowManager(27973): 	at android.view.ViewRootImpl.<init>(ViewRootImpl.java:346)
E/WindowManager(27973): 	at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:248)
E/WindowManager(27973): 	at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:69)
E/WindowManager(27973): 	at android.app.Dialog.show(Dialog.java:286)
E/WindowManager(27973): 	at acr.browser.lightning.fe.onPreExecute(Unknown Source)
E/WindowManager(27973): 	at android.os.AsyncTask.executeOnExecutor(AsyncTask.java:587)
E/WindowManager(27973): 	at android.os.AsyncTask.execute(AsyncTask.java:535)
E/WindowManager(27973): 	at acr.browser.lightning.ReadingActivity.a(Unknown Source)
E/WindowManager(27973): 	at acr.browser.lightning.ReadingActivity.onCreate(Unknown Source)
E/WindowManager(27973): 	at android.app.Activity.performCreate(Activity.java:5241)
E/WindowManager(27973): 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087)
E/WindowManager(27973): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2151)
E/WindowManager(27973): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2236)
E/WindowManager(27973): 	at android.app.ActivityThread.access$800(ActivityThread.java:138)
E/WindowManager(27973): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1199)
E/WindowManager(27973): 	at android.os.Handler.dispatchMessage(Handler.java:102)
E/WindowManager(27973): 	at android.os.Looper.loop(Looper.java:136)
E/WindowManager(27973): 	at android.app.ActivityThread.main(ActivityThread.java:5034)
E/WindowManager(27973): 	at java.lang.reflect.Method.invoke(Native Method)
E/WindowManager(27973): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:795)
E/WindowManager(27973): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:611)
```
Android 4.4, Nexus 4.

**Comment by karolba** [comment]
I just discovered that this doesn't happen in a debug (```ant debug```) build. Probably a ProGuard issue.

**Comment by anthonycr** [comment]
Okay, yeah that's likely a proguard issue I'll have to fix. Thank you. I should have checked before publishing

**Comment by karolba** [comment]
Why did I left it open? Closing.
