### ISSUE TITLE
App force Closes instantly on Android M Preview 2

### ISSUE THREAD

**Issue by nmac143** [anthonycr/Lightning-Browser#272]
Upon opening the app in Android M Preview 2 on the Nexus 5.

I get this error
```
08-05 20:58:23.172  16452-16452/acr.browser.lightning D/AndroidRuntime﹕ Shutting down VM
08-05 20:58:23.174  16452-16452/acr.browser.lightning E/AndroidRuntime﹕ FATAL EXCEPTION: main
    Process: acr.browser.lightning, PID: 16452
    java.lang.RuntimeException: Unable to start activity ComponentInfo{acr.browser.lightning/acr.browser.lightning.activity.MainActivity}: java.lang.SecurityException: Permission Denial: opening provider com.android.browser.provider.BrowserProviderProxy from ProcessRecord{fef0e55 16452:acr.browser.lightning/u0a142} (pid=16452, uid=10142) requires com.android.browser.permission.READ_HISTORY_BOOKMARKS or com.android.browser.permission.WRITE_HISTORY_BOOKMARKS
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2417)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2477)
            at android.app.ActivityThread.-wrap11(ActivityThread.java)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1345)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:148)
            at android.app.ActivityThread.main(ActivityThread.java:5415)
            at java.lang.reflect.Method.invoke(Native Method)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:725)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:615)
     Caused by: java.lang.SecurityException: Permission Denial: opening provider com.android.browser.provider.BrowserProviderProxy from ProcessRecord{fef0e55 16452:acr.browser.lightning/u0a142} (pid=16452, uid=10142) requires com.android.browser.permission.READ_HISTORY_BOOKMARKS or com.android.browser.permission.WRITE_HISTORY_BOOKMARKS
            at android.os.Parcel.readException(Parcel.java:1599)
            at android.os.Parcel.readException(Parcel.java:1552)
            at android.app.ActivityManagerProxy.getContentProvider(ActivityManagerNative.java:3511)
            at android.app.ActivityThread.acquireProvider(ActivityThread.java:4776)
            at android.app.ContextImpl$ApplicationContentResolver.acquireUnstableProvider(ContextImpl.java:1981)
            at android.content.ContentResolver.acquireUnstableProvider(ContentResolver.java:1466)
            at android.content.ContentResolver.query(ContentResolver.java:473)
            at android.content.ContentResolver.query(ContentResolver.java:432)
            at acr.browser.lightning.activity.BrowserActivity.E(Unknown Source)
            at acr.browser.lightning.activity.BrowserActivity.z(Unknown Source)
            at acr.browser.lightning.activity.BrowserActivity.onCreate(Unknown Source)
            at acr.browser.lightning.activity.MainActivity.onCreate(Unknown Source)
            at android.app.Activity.performCreate(Activity.java:6162)
            at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1107)
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2370)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2477)
            at android.app.ActivityThread.-wrap11(ActivityThread.java)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1345)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:148)
            at android.app.ActivityThread.main(ActivityThread.java:5415)
            at java.lang.reflect.Method.invoke(Native Method)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:725)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:615)
```

video

**Comment by anthonycr** [comment]
Thanks for the heads up, I haven't updated for Android M yet.

**Comment by anthonycr** [comment]
Temporarily fixed until I add in the correct permission handling
