### ISSUE TITLE
Lightning crashes when clicking (with a mouse) on the URL box under certain conditions

### ISSUE THREAD

**Issue by Zoraver** [anthonycr/Lightning-Browser#419]
If the URL Box Contents preference is set to either domain or title, Lightning will crash if the URL box is clicked with a mouse on the area to the right of the displayed text and to the left of the refresh / stop button.  This does not occur when the URL Box Contents preference is set to display the raw URL.

This issue was observed on an Asus TF300T using the trackpad built into its keyboard dock.

Logcat shows the following when this occurs:

`04-30 21:09:26.466 2954-2954/acr.browser.barebones E/InputEventReceiver: Exception dispatching input event.
04-30 21:09:26.466 2954-2954/acr.browser.barebones E/MessageQueue-JNI: Exception in MessageQueue callback: handleReceiveCallback
04-30 21:09:26.475 2954-2954/acr.browser.barebones E/MessageQueue-JNI: java.lang.IndexOutOfBoundsException: setSpan (26 ... 26) ends beyond length 19
                                                                           at android.text.SpannableStringBuilder.checkRange(SpannableStringBuilder.java:1090)
                                                                           at android.text.SpannableStringBuilder.setSpan(SpannableStringBuilder.java:665)
                                                                           at android.text.SpannableStringBuilder.setSpan(SpannableStringBuilder.java:658)
                                                                           at android.text.method.ArrowKeyMovementMethod.onTouchEvent(ArrowKeyMovementMethod.java:258)
                                                                           at android.widget.TextView.onTouchEvent(TextView.java:8325)
                                                                           at android.view.View.dispatchTouchEvent(View.java:9300)
                                                                           at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2553)
                                                                           at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2197)
                                                                           at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2553)
                                                                           at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2197)
                                                                           at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2553)
                                                                           at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2197)
                                                                           at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2553)
                                                                           at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2197)
                                                                           at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2553)
                                                                           at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2197)
                                                                           at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2553)
                                                                           at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2197)
                                                                           at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2553)
                                                                           at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2197)
                                                                           at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2553)
                                                                           at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2197)
                                                                           at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2553)
                                                                           at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2197)
                                                                           at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2553)
                                                                           at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2197)
                                                                           at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2553)
                                                                           at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2197)
                                                                           at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2553)
                                                                           at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2197)
                                                                           at com.android.internal.policy.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java:2403)
                                                                           at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1737)
                                                                           at android.app.Activity.dispatchTouchEvent(Activity.java:2771)
                                                                           at android.support.v7.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:60)
                                                                           at android.support.v7.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:60)
                                                                           at com.android.internal.policy.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java:2364)
                                                                           at android.view.View.dispatchPointerEvent(View.java:9520)
                                                                           at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4230)
                                                                           at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4096)
                                                                           at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3642)
                                                                           at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3695)
                                                                           at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3661)
                                                                           at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:3787)
                                                                           at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3669)
                                                                           at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:3844)
                                                                           at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3642)
                                                                           at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3695)
                                                                           at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3661)
                                                                           at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3669)
                                                                           at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3642)
                                                                           at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:5922)
                                                                           at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:5896)
                                                                        at android.view.
04-30 21:09:26.475 2954-2954/acr.browser.barebones D/AndroidRuntime: Shutting down VM
--------- beginning of crash
04-30 21:09:26.476 2954-2954/acr.browser.barebones E/AndroidRuntime: FATAL EXCEPTION: main
                                                                     Process: acr.browser.barebones, PID: 2954
                                                                     java.lang.IndexOutOfBoundsException: setSpan (26 ... 26) ends beyond length 19
                                                                         at android.text.SpannableStringBuilder.checkRange(SpannableStringBuilder.java:1090)
                                                                         at android.text.SpannableStringBuilder.setSpan(SpannableStringBuilder.java:665)
                                                                         at android.text.SpannableStringBuilder.setSpan(SpannableStringBuilder.java:658)
                                                                         at android.text.method.ArrowKeyMovementMethod.onTouchEvent(ArrowKeyMovementMethod.java:258)
                                                                         at android.widget.TextView.onTouchEvent(TextView.java:8325)
                                                                         at android.view.View.dispatchTouchEvent(View.java:9300)
                                                                         at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2553)
                                                                         at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2197)
                                                                         at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2553)
                                                                         at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2197)
                                                                         at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2553)
                                                                         at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2197)
                                                                         at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2553)
                                                                         at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2197)
                                                                         at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2553)
                                                                         at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2197)
                                                                         at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2553)
                                                                         at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2197)
                                                                         at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2553)
                                                                         at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2197)
                                                                         at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2553)
                                                                         at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2197)
                                                                         at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2553)
                                                                         at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2197)
                                                                         at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2553)
                                                                         at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2197)
                                                                         at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2553)
                                                                         at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2197)
                                                                         at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2553)
                                                                         at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2197)
                                                                         at com.android.internal.policy.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java:2403)
                                                                         at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1737)
                                                                         at android.app.Activity.dispatchTouchEvent(Activity.java:2771)
                                                                         at android.support.v7.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:60)
                                                                         at android.support.v7.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:60)
                                                                         at com.android.internal.policy.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java:2364)
                                                                         at android.view.View.dispatchPointerEvent(View.java:9520)
                                                                         at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4230)
                                                                         at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4096)
                                                                         at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3642)
                                                                         at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3695)
                                                                         at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3661)
                                                                         at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:3787)
                                                                         at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3669)
                                                                         at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:3844)
                                                                         at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3642)
                                                                         at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3695)
                                                                         at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3661)
                                                                         at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3669)
                                                                         at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3642)
                                                                         at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:5922)
                                                                        at android.view.ViewRootImpl.`

**Comment by Zoraver** [comment]
This is fixed in the latest version.
