### ISSUE TITLE
crash application 4.4.4 

### ISSUE THREAD

**Issue by mehul-vrinsoft** [anthonycr/Lightning-Browser#547]
its seems like 
 Caused by: org.xmlpull.v1.XmlPullParserException: Binary XML file line #1: invalid drawable tag vector
                                                                           at android.graphics.drawable.Drawable.createFromXmlInner(Drawable.java:969)
                                                                           at android.graphics.drawable.Drawable.createFromXml(Drawable.java:913)
                                                                           at android.content.res.Resources.loadDrawable(Resources.java:3449)
                                                                           at android.content.res.Resources.getDrawable(Resources.java:1896)

**Comment by HunterLeo** [comment]
You can insert the following codes in BrowserActivity.java:
`static {AppCompatDelegate.setCompatVectorFromResourcesEnabled(true);}`

And  then Clean Project->Run,that's OK!


@anthonycr ,please update,thanks!
