### ISSUE TITLE
A resource was acquired at attached stack trace but never released. See java.io.Closeable for information on avoiding resource leaks.

### ISSUE THREAD

**Issue by mehul-vrinsoft** [anthonycr/Lightning-Browser#583]
A resource was acquired at attached stack trace but never released. See java.io.Closeable for information on avoiding resource leaks.
```
java.lang.Throwable: Explicit termination method 'close' not called
                                                                     at dalvik.system.CloseGuard.open(CloseGuard.java:180)
                                                                     at java.io.FileOutputStream.<init>(FileOutputStream.java:222)
                                                                     at android.app.ContextImpl.openFileOutput(ContextImpl.java:514)
                                                                     at android.content.ContextWrapper.openFileOutput(ContextWrapper.java:199)
                                                                     at blg.a(:com.google.android.gms.DynamiteModulesC:16)
                                                                     at bkf.c(:com.google.android.gms.DynamiteModulesC:99)
                                                                     at bkf.b(:com.google.android.gms.DynamiteModulesC:74)
                                                                     at bkw.run(:com.google.android.gms.DynamiteModulesC:19)
                                                                     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
                                                                     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
                                                                     at java.lang.Thread.run(Thread.java:762)
```

**Comment by anthonycr** [comment]
This looks like a stacktrace from google play services, which Lightning does not use. I'm going to close this, please comment back and reopen if you have more information.
