### ISSUE TITLE
Issue with Building apk

### ISSUE THREAD

**Issue by brownstic** [anthonycr/Lightning-Browser#723]
Tried building apk and ran into this error.

`Fatal exception
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.smappbrowser/acr.browser.lightning.MainActivity}: android.view.InflateException: Binary XML file line #26: Binary XML file line #16: Error inflating class TextView
FATAL EXCEPTION: main
Process: com.smappbrowser, PID: 8623
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.smappbrowser/acr.browser.lightning.MainActivity}: android.view.InflateException: Binary XML file line #26: Binary XML file line #16: Error inflating class TextView
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2665)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2726)
	at android.app.ActivityThread.-wrap12(ActivityThread.java)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1477)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:154)
	at android.app.ActivityThread.main(ActivityThread.java:6119)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
Caused by: android.view.InflateException: Binary XML file line #26: Binary XML file line #16: Error inflating class TextView
Caused by: android.view.InflateException: Binary XML file line #16: Error inflating class TextView
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean androidx.appcompat.widget.av.d()' on a null object reference
	at androidx.appcompat.widget.AppCompatTextView.onTextChanged(Unknown Source)
	at android.widget.TextView.setText(TextView.java:4484)
	at android.widget.TextView.setText(TextView.java:4337)
	at android.widget.TextView.<init>(TextView.java:1442)
	at android.widget.TextView.<init>(TextView.java:704)
	at androidx.appcompat.widget.AppCompatTextView.<init>(Unknown Source)
	at androidx.appcompat.widget.AppCompatTextView.<init>(Unknown Source)
	at androidx.appcompat.app.AppCompatViewInflater.a(Unknown Source)
	at androidx.appcompat.app.AppCompatDelegateImpl.a(Unknown Source)
	at androidx.appcompat.app.AppCompatDelegateImpl.onCreateView(Unknown Source)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:769)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:727)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:858)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:821)
	at android.view.LayoutInflater.parseInclude(LayoutInflater.java:994)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:854)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:821)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:861)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:821)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:861)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:821)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:518)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:426)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:377)
	at androidx.appcompat.app.AppCompatDelegateImpl.b(Unknown Source)
	at androidx.appcompat.app.AppCompatActivity.setContentView(Unknown Source)
	at acr.browser.lightning.browser.activity.BrowserActivity.onCreate(Unknown Source)
	at android.app.Activity.performCreate(Activity.java:6679)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1118)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2618)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2726)
	at android.app.ActivityThread.-wrap12(ActivityThread.java)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1477)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:154)
	at android.app.ActivityThread.main(ActivityThread.java:6119)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)`

Any help will be greatly appreciated

**Comment by brownstic** [comment]
@Younes-L sadly no, do u have the same problem?

**Comment by diybl** [comment]
debug is run
but release i have the same problom with you

**Comment by diybl** [comment]
https://github.com/ArthurHub/Android-Image-Cropper/issues/481

this can solve
