### ISSUE TITLE
use lightning can't download file

### ISSUE THREAD

**Issue by tytok** [anthonycr/Lightning-Browser#818]
I find a question：
nothing happen when I use lightning  download  a file from website？

**Comment by tytok** [comment]
D/eglCodecCommon: setVertexArrayObject: set vao to 1 (1) 11 7
D/eglCodecCommon: setVertexArrayObject: set vao to 0 (0) 11 3
D/eglCodecCommon: setVertexArrayObject: set vao to 1 (1) 11 7
D/eglCodecCommon: setVertexArrayObject: set vao to 0 (0) 11 3
E/BaseSuggestionsModel: Problem getting search suggestions
    java.net.SocketTimeoutException: failed to connect to suggestqueries.google.com/172.217.160.78 (port 443) from /192.168.232.2 (port 48612) after 10000ms
        at libcore.io.IoBridge.connectErrno(IoBridge.java:191)
        at libcore.io.IoBridge.connect(IoBridge.java:135)
        at java.net.PlainSocketImpl.socketConnect(PlainSocketImpl.java:142)
        at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:390)
        at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:230)
        at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:212)
        at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:436)
        at java.net.Socket.connect(Socket.java:621)
        at okhttp3.internal.platform.AndroidPlatform.connectSocket(AndroidPlatform.java:71)
        at okhttp3.internal.connection.RealConnection.connectSocket(RealConnection.java:263)
        at okhttp3.internal.connection.RealConnection.connect(RealConnection.java:183)
        at okhttp3.internal.connection.ExchangeFinder.findConnection(ExchangeFinder.java:224)
        at okhttp3.internal.connection.ExchangeFinder.findHealthyConnection(ExchangeFinder.java:108)
        at okhttp3.internal.connection.ExchangeFinder.find(ExchangeFinder.java:88)
        at okhttp3.internal.connection.Transmitter.newExchange(Transmitter.java:169)
        at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:41)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
        at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:94)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
        at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
        at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:88)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
        at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:229)
        at okhttp3.RealCall.execute(RealCall.java:81)
        at acr.browser.lightning.search.suggestions.BaseSuggestionsModel.downloadSuggestionsForQuery(BaseSuggestionsModel.kt:77)
        at acr.browser.lightning.search.suggestions.BaseSuggestionsModel.access$downloadSuggestionsForQuery(BaseSuggestionsModel.kt:20)
        at acr.browser.lightning.search.suggestions.BaseSuggestionsModel$resultsForSearch$1$1.call(BaseSuggestionsModel.kt:58)
        at acr.browser.lightning.search.suggestions.BaseSuggestionsModel$resultsForSearch$1$1.call(BaseSuggestionsModel.kt:20)
        at io.reactivex.internal.operators.single.SingleFromCallable.subscribeActual(SingleFromCallable.java:44)
        at io.reactivex.Single.subscribe(Single.java:3666)
        at io.reactivex.internal.operators.single.SingleFlatMap$SingleFlatMapCallback.onSuccess(SingleFlatMap.java:84)
        at io.reactivex.internal.operators.single.SingleCache.subscribeActual(SingleCache.java:59)
        at io.reactivex.Single.subscribe(Single.java:3666)
        at io.reactivex.internal.operators.single.SingleFlatMap.subscribeActual(SingleFlatMap.java:36)
        at io.reactivex.Single.subscribe(Single.java:3666)
        at io.reactivex.internal.operators.flowable.FlowableFlatMapSingle$FlatMapSingleSubscriber.onNext(FlowableFlatMapSingle.java:132)
        at io.reactivex.internal.operators.flowable.FlowableRefCount$RefCountSubscriber.onNext(FlowableRefCount.java:229)
        at io.reactivex.internal.operators.flowable.FlowablePublishAlt$PublishConnection.drain(FlowablePublishAlt.java:317)
        at io.reactivex.internal.operators.flowable.FlowablePublishAlt$PublishConnection.onNext(FlowablePublishAlt.java:239)
E/BaseSuggestionsModel:     at io.reactivex.internal.operators.flowable.FlowableFilter$FilterSubscriber.tryOnNext(FlowableFilter.java:74)
        at io.reactivex.internal.operators.flowable.FlowableFilter$FilterSubscriber.onNext(FlowableFilter.java:52)
        at io.reactivex.internal.operators.flowable.FlowableMap$MapConditionalSubscriber.onNext(FlowableMap.java:111)
        at io.reactivex.internal.operators.flowable.FlowableOnBackpressureLatest$BackpressureLatestSubscriber.drain(FlowableOnBackpressureLatest.java:129)
        at io.reactivex.internal.operators.flowable.FlowableOnBackpressureLatest$BackpressureLatestSubscriber.onNext(FlowableOnBackpressureLatest.java:68)
        at io.reactivex.internal.operators.flowable.FlowableFromObservable$SubscriberObserver.onNext(FlowableFromObservable.java:54)
        at io.reactivex.internal.operators.observable.ObservableHide$HideDisposable.onNext(ObservableHide.java:67)
        at io.reactivex.subjects.PublishSubject$PublishDisposable.onNext(PublishSubject.java:308)
        at io.reactivex.subjects.PublishSubject.onNext(PublishSubject.java:228)
        at acr.browser.lightning.search.SuggestionsAdapter$SearchFilter.performFiltering(SuggestionsAdapter.kt:233)
        at android.widget.Filter$RequestHandler.handleMessage(Filter.java:236)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:214)
        at android.os.HandlerThread.run(HandlerThread.java:67)
D/eglCodecCommon: setVertexArrayObject: set vao to 1 (1) 11 7
D/eglCodecCommon: setVertexArrayObject: set vao to 0 (0) 11 3
D/eglCodecCommon: setVertexArrayObject: set vao to 1 (1) 11 7
D/eglCodecCommon: setVertexArrayObject: set vao to 0 (0) 11 3
D/StrictMode: StrictMode policy violation: android.os.strictmode.UntaggedSocketViolation: Untagged socket detected; use TrafficStats.setThreadSocketTag() to track all network usage
        at android.os.StrictMode.onUntaggedSocket(StrictMode.java:2124)
        at com.android.server.NetworkManagementSocketTagger.tag(NetworkManagementSocketTagger.java:82)
        at libcore.io.BlockGuardOs.tagSocket(BlockGuardOs.java:52)
        at libcore.io.BlockGuardOs.socket(BlockGuardOs.java:372)
        at libcore.io.ForwardingOs.socket(ForwardingOs.java:217)
        at libcore.io.IoBridge.socket(IoBridge.java:658)
        at java.net.PlainSocketImpl.socketCreate(PlainSocketImpl.java:128)
        at java.net.AbstractPlainSocketImpl.create(AbstractPlainSocketImpl.java:128)
        at java.net.Socket.createImpl(Socket.java:489)
        at java.net.Socket.getImpl(Socket.java:552)
        at java.net.Socket.setSoTimeout(Socket.java:1180)
        at okhttp3.internal.connection.RealConnection.connectSocket(RealConnection.java:261)
        at okhttp3.internal.connection.RealConnection.connect(RealConnection.java:183)
        at okhttp3.internal.connection.ExchangeFinder.findConnection(ExchangeFinder.java:224)
        at okhttp3.internal.connection.ExchangeFinder.findHealthyConnection(ExchangeFinder.java:108)
        at okhttp3.internal.connection.ExchangeFinder.find(ExchangeFinder.java:88)
        at okhttp3.internal.connection.Transmitter.newExchange(Transmitter.java:169)
        at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:41)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
        at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:94)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
        at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
        at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:88)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
        at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:229)
        at okhttp3.RealCall.execute(RealCall.java:81)
        at acr.browser.lightning.search.suggestions.BaseSuggestionsModel.downloadSuggestionsForQuery(BaseSuggestionsModel.kt:77)
        at acr.browser.lightning.search.suggestions.BaseSuggestionsModel.access$downloadSuggestionsForQuery(BaseSuggestionsModel.kt:20)
        at acr.browser.lightning.search.suggestions.BaseSuggestionsModel$resultsForSearch$1$1.call(BaseSuggestionsModel.kt:58)
        at acr.browser.lightning.search.suggestions.BaseSuggestionsModel$resultsForSearch$1$1.call(BaseSuggestionsModel.kt:20)
        at io.reactivex.internal.operators.single.SingleFromCallable.subscribeActual(SingleFromCallable.java:44)
        at io.reactivex.Single.subscribe(Single.java:3666)
        at io.reactivex.internal.operators.single.SingleFlatMap$SingleFlatMapCallback.onSuccess(SingleFlatMap.java:84)
        at io.reactivex.internal.operators.single.SingleCache.subscribeActual(SingleCache.java:59)
        at io.reactivex.Single.subscribe(Single.java:3666)
        at io.reactivex.internal.operators.single.SingleFlatMap.subscribeActual(SingleFlatMap.java:36)
        at io.reactivex.Single.subscribe(Single.java:3666)
        at io.reactivex.internal.operators.flowable.FlowableFlatMapSingle$FlatMapSingleSubscriber.onNext(FlowableFlatMapSingle.java:132)
        at io.reactivex.internal.operators.flowable.FlowableRefCount$RefCountSubscriber.onNext(FlowableRefCount.java:229)
        at io.reactivex.internal.operators.flowable.FlowablePublishAlt$PublishConnection.drain(FlowablePublishAlt.java:317)
        at io.reactivex.internal.operators.flowable.FlowablePublishAlt$PublishConnection.onNext(FlowablePublishAlt.java:239)
    	at io.reactivex.internal.operators.flowable.FlowableFilter$FilterSubscriber.tryOnNext(FlowableFilter.jav
D/eglCodecCommon: setVertexArrayObject: set vao to 1 (1) 11 7
D/eglCodecCommon: setVertexArrayObject: set vao to 0 (0) 11 3
D/eglCodecCommon: setVertexArrayObject: set vao to 1 (1) 11 7
